# Generated by Django 3.0.7 on 2020-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='closing_time',
            field=models.TimeField(),
        ),
    ]
