# Generated by Django 3.0.7 on 2020-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20200609_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
